### ISSUE TITLE
--setCWND not respected in split config case

### ISSUE THREAD

**Issue by mommsen** [stiegerb/daq2val#20]
Hi Benjamin,

I tried to use ./daq2Control/runDAQ2Scan.py --setCWND 140000 for cDAQ. However, the value has not been taken into account, i.e. the FEROL controller was using the one from the configuration file. It works fine in daq2val. I suspect that it is due to the split config being used for cDAQ. But I was not able to locate the bug.

Remi

**Comment by stiegerb** [comment]
Hi Remi,
Yes, that's because of what we discussed last week in the context of the dynamic RU masking. I had sent you a fix for that, but it needs some testing.
Check: https://github.com/stiegerb/daq2val/compare/maskRUsOnEVM

Cheers,
Benjamin

**Comment by stiegerb** [comment]
Give me some time and I'll commit a fix later.

**Comment by stiegerb** [comment]
Ok, I pushed a new version that should fix this issue. I only tested with --dry locally, so there might still be hidden bugs, but I don't expect it.

https://github.com/stiegerb/daq2val/commit/aa3ac32d59ff1549b9acfeaac92cd14281a21a60
